"""Initial migration.

Revision ID: a39c0a636e00
Revises: 
Create Date: 2024-10-02 11:22:05.368140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39c0a636e00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('metrics_question1', sa.Text(), nullable=True),
    sa.Column('metrics_question2', sa.Text(), nullable=True),
    sa.Column('metrics_question3', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Integer(), nullable=True),
    sa.Column('metrics_comments', sa.Text(), nullable=True),
    sa.Column('metrics_question_answered', sa.Boolean(), nullable=False),
    sa.Column('economic_buyer_question1', sa.Text(), nullable=True),
    sa.Column('economic_buyer_question2', sa.Text(), nullable=True),
    sa.Column('economic_buyer_question3', sa.Text(), nullable=True),
    sa.Column('economic_buyer', sa.Integer(), nullable=True),
    sa.Column('economic_buyer_comments', sa.Text(), nullable=True),
    sa.Column('economic_buyer_question_answered', sa.Boolean(), nullable=False),
    sa.Column('decision_criteria_question1', sa.Text(), nullable=True),
    sa.Column('decision_criteria_question2', sa.Text(), nullable=True),
    sa.Column('decision_criteria_question3', sa.Text(), nullable=True),
    sa.Column('decision_criteria', sa.Integer(), nullable=True),
    sa.Column('decision_criteria_comments', sa.Text(), nullable=True),
    sa.Column('decision_criteria_question_answered', sa.Boolean(), nullable=False),
    sa.Column('decision_process_question1', sa.Text(), nullable=True),
    sa.Column('decision_process_question2', sa.Text(), nullable=True),
    sa.Column('decision_process_question3', sa.Text(), nullable=True),
    sa.Column('decision_process', sa.Integer(), nullable=True),
    sa.Column('decision_process_comments', sa.Text(), nullable=True),
    sa.Column('decision_process_question_answered', sa.Boolean(), nullable=False),
    sa.Column('paper_process_question1', sa.Text(), nullable=True),
    sa.Column('paper_process_question2', sa.Text(), nullable=True),
    sa.Column('paper_process_question3', sa.Text(), nullable=True),
    sa.Column('paper_process', sa.Integer(), nullable=True),
    sa.Column('paper_process_comments', sa.Text(), nullable=True),
    sa.Column('paper_process_question_answered', sa.Boolean(), nullable=False),
    sa.Column('implications_of_pain_question1', sa.Text(), nullable=True),
    sa.Column('implications_of_pain_question2', sa.Text(), nullable=True),
    sa.Column('implications_of_pain_question3', sa.Text(), nullable=True),
    sa.Column('implications_of_pain', sa.Integer(), nullable=True),
    sa.Column('implications_of_pain_comments', sa.Text(), nullable=True),
    sa.Column('implications_of_pain_question_answered', sa.Boolean(), nullable=False),
    sa.Column('champion_question1', sa.Text(), nullable=True),
    sa.Column('champion_question2', sa.Text(), nullable=True),
    sa.Column('champion_question3', sa.Text(), nullable=True),
    sa.Column('champion', sa.Integer(), nullable=True),
    sa.Column('champion_comments', sa.Text(), nullable=True),
    sa.Column('champion_question_answered', sa.Boolean(), nullable=False),
    sa.Column('competition_question1', sa.Text(), nullable=True),
    sa.Column('competition_question2', sa.Text(), nullable=True),
    sa.Column('competition_question3', sa.Text(), nullable=True),
    sa.Column('competition', sa.Integer(), nullable=True),
    sa.Column('competition_comments', sa.Text(), nullable=True),
    sa.Column('competition_question_answered', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(length=50), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('project')
    # ### end Alembic commands ###
